name: perper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.13.7
  fancy_drawer: ^2.0.0
  shared_preferences: ^2.2.3
  reactive_theme: ^2.1.0
  sizer: ^2.0.15
  google_fonts: ^6.2.1
  http: ^1.2.1
  cool_alert: ^2.0.1
  flutter_stripe: ^5.0.0  # Ensure this line is present
  intl: ^0.19.0
  video_player: ^2.2.10
lottie: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
